### PR TITLE
ruciomover: api only from now on, traces off

### PR DESCRIPTION
**Pull request by TomasJavurek**
Traces are switched off by settings of upload/download client. This is introduced in Rucio just very recently, thus the hasattr(). 

Both download and upload will be called from the ruciomover directly, not over CLI. This needs testing, since shell env. might differ a bit from python.

### CODE REVIEW

**Comment by TomasJavurek** [comment]
Not so easily. Problem is, that Pavlo implemented the traces using cli rucio command. But I removed now cli commands completely. Thus, it is complaining.

**Comment by PalNilsson** [comment]
I'm seeing some unusual (?) errors in the test jobs, can you please check
https://bigpanda.cern.ch/jobs/?prodsourcelabel=rc_test&days=5&piloterrorcode=1099&hours=120&display_limit=100
and
https://bigpanda.cern.ch/jobs/?prodsourcelabel=rc_test&days=5&piloterrorcode=1137&hours=120&display_limit=100

**Comment by PalNilsson** [comment]
Have you check the test jobs? I probably need to present the new pilot in ADC Weekly today. Can it be released?

**Comment by TomasJavurek** [comment]
Looking at the jobs:
https://bigpanda.cern.ch/jobs/?prodsourcelabel=rc_test&days=5&piloterrorcode=1099&hours=120&display_limit=100

these are analysis jobs and direct io is used istead of stagein. They doesn't seem to fail due to rucio mover in case of stagein. For stageout, still the old command was used:

2018-11-01 07:59:53| 585533|Singularity.| Using command rucio -v upload --guid 96f9795a-c60e-46d7-9865-935ec313cf1e --no-register --rse IN2P3-LPSC_DATADISK --scope hc_test output.1.f03ee5b3-b034-40c1-bbde-9229b89ef86b_48061.pool.root
2018-11-01 07:59:53| 585533|rucio_sitemo| stageOutCmd: rucio -v upload --guid 96f9795a-c60e-46d7-9865-935ec313cf1e --no-register --rse IN2P3-LPSC_DATADISK --scope hc_test output.1.f03ee5b3-b034-40c1-bbde-9229b89ef86b_48061.pool.root

but that is not part of rucio_sitemover code anymore. So, it doesn't seem the newest version to be used.


2018-11-01 07:58:30| 585533|mover.py    | Direct access mode will be used for lfn=AOD.05536542._000001.pool.root.1 .. skip transfer for this file

**Comment by PalNilsson** [comment]
I had no choice but to revert the changes because I have to release the pilot, so please make another pull request and I will merge it after the pilot has been released. We need to restart the HC jobs as well. It might take a few days.

**Pull request merged**
