### PR TITLE
right sorting of replicas

### PR DESCRIPTION
**Pull request by TomasJavurek**
pls really check this pull request, it is bit messy and needs to be cerfully checked.

### CODE REVIEW

**Comment by anisyonk** [comment]
Tomas, 
you did not run a test job, right?

from my view, it will not work:)

**Comment by TomasJavurek** [comment]
No, take it as suggestion. I need somebody to test it.

**Comment by PalNilsson** [comment]
I can help test it on Monday no problem. Thanks, Paul

Sent from my iPhone

On 11 Aug 2018, at 20:48, javor <notifications@github.com<mailto:notifications@github.com>> wrote:

No, take it as suggestion. I need somebody to test it.

**Comment by anisyonk** [comment]
the logic is broken.

1. you removed default protocol resolved from `aprotocols` which is bad, since it could be used for corner cases.
2. you kept only the first protocol from the rucio which is also not so good, since sitemover could not support it.

Normally in the `resolve_replicas` you just need to add 2 lines:

1. create a dictionary with manually sorted list of available replicas according to the priorities by ddmendpoint -- this hack will be removed once Rucio deliver the update this week.
2. instead of adding `r['rses'][ddm]` into the `fdat.replicas`
```fdat.replicas.append((ddm, r['rses'][ddm], ddm_se, ddm_path))```
a new data from the dict create at first step should be passed -- this fix can be also removed once Rucio deliver the fix

If Rucio will deliver patch this week with resolved sort server-side, no needs at all to apply any fixed to the `mover.resolve_replicas()` function.

**Comment by TomasJavurek** [comment]
Hi Alexey,

I think we agreed not to have copytool fallbacks. Also fetching the AGIS is
not needed, because rucio wouldn't return pfn with not-existing protocol.
But ok, we don't need to slove it after Mario's fix. I think, we should
leave the fallbacks up to rucio in pilot2.

Tomas.

**Comment by anisyonk** [comment]
this is not a fallback, just use of  different copytool, e.g. if a site wants to use non rucio sitemover, e.g. xrdcp, so that we need to pick up root:// protocol.

**Comment by PalNilsson** [comment]
Closing this one. Replaced with pull request #220.

**Pull request closed without merging**
