### PR TITLE
As proposed here https://github.com/PanDAWMS/pilot/pull/127#issuecomment-294744079

### PR DESCRIPTION
**Pull request by complynx**

### CODE REVIEW

**Comment by PalNilsson** [comment]
Why are you hardcoding file names in SiteInformation.py? Cheers, Paul

**Comment by complynx** [comment]
I can't understand the question. I don't use any filenames.

**Comment by PalNilsson** [comment]
p = "--maxEvents=2 --inputHITSFile HITS.06828093._000096.pool.root.1 --outputRDOFile RDO_20c37551-abfd-4ce1-b0ae-09a0a5b72484.root --useTestASetup --useTestXRootD"

**Comment by complynx** [comment]
This is test code. It is in the section __name__ == "__main__", so it is not invoked if it's pilot.
The next time, please use inline comments feature in Github to comment or reference the code directly.

**Comment by PalNilsson** [comment]
OK thanks. I will test it.

**Comment by PalNilsson** [comment]
2017-04-26 15:15:18| 31513|RunJob.py   | !!FAILED!!3001!! Exception caught in RunJob: get() takes at most 3 arguments (4 given), Traceback (most recent call last):
  File \"RunJob.py\", line 1728, in <module>
    ec, runCommandList, job, multi_trf = runJob.setup(job, jobSite, thisExperiment)
  File \"RunJob.py\", line 600, in setup
    ec, job.pilotErrorDiag, cmd, job.spsetup, job.JEM, job.cmtconfig = thisExperiment.getJobExecutionCommand(job, jobSite, self.__pilot_initdir)
  File \"/scratch/Panda_Pilot_29105_1493219705/PandaJob_3350317981_1493219714/ATLASExperiment.py\", line 371, in getJobExecutionCommand
    x=si.getLocalROOTSetup()
  File \"/scratch/Panda_Pilot_29105_1493219705/PandaJob_3350317981_1493219714/ATLASSiteInformation.py\", line 759, in getLocalROOTSetup
    if os.environ.get(\"TestXRootD\", 'True', 'False') == 'True' or hasattr(self, 'xrootd_test') and self.xrootd_test:
TypeError: get() takes at most 3 arguments (4 given)

Please fix.

**Pull request merged**
