### PR TITLE
allow esmerge to select closest inputs

### PR DESCRIPTION
**Pull request by wguanicedew**
ES at NERSC plans to transfer unmerge zip files to other storages.
Pilot needs to allow esmerge job to select closest inputs to stagein.

### CODE REVIEW

**Comment by PalNilsson** [comment]
Mario can you please review this? Is this what ATLAS wants in general / does it have implications? Just making sure so we don't do something drastic here.

**Comment by mlassnig** [comment]
Just arrived at GVA airport, will have a look soon.

**Comment by PalNilsson** [comment]
Yes, that's what I suspected. Wen, please start a discussion with Ale and then he will comment. This pilot version will not be released as a hotfix but with the formal/normal release, so it will anyway be presented in the ADC Weekly. But better to inform ADC people in advance. The isDeterministic boolean comes from the AGIS ddm configuration (@anisyonk may comment for details).

**Comment by wguanicedew** [comment]
1) file.replicas is None but we still try to stagein. It's not normal jobs(for normal jobs if file.replicas is None, the job will fail with no replicas.). It can only happen for ES merge jobs.
2) isDeterministic  is True. It means it's not objectstore. Currently it's only NERSC_DATADISK. Doug wants to move the es outputs from NERSC_DATADISK to somewhere else and then the esmerge job can stagein from that place(currently es merge job can run at CERN or somewhere, and remotely stagein from NERSC_DATADISK).
I am updating it.

**Comment by mlassnig** [comment]
if it's only for es jobs, then conceptually this is fine

**Comment by wguanicedew** [comment]
It includes two parts.
1) on line 314, to allow remote replicas if fdata.storageId is defined (only for esmerge jobs the storageId is defined). Normally if there is no replication rule, es unmerge files will only be stored at one place. This modification will not change anything. If es unmerge fiels are replicated to somewhere else, this update will allow esmerge job to read from all available places (currently this situation will only happen on NERSC es jobs).
2) fix the checksum and filesize warning messages(it only changes the log messages).

**Comment by wguanicedew** [comment]
The test job was started in parallel. (My fault, I should close old pull request. Otherwise new commits will go to the pull request automatically.)

**Pull request merged**
