### PR TITLE
Fix for https://its.cern.ch/jira/browse/ATLASPANDA-322?focusedComment…

### PR DESCRIPTION
**Pull request by complynx**
[Issue description](https://its.cern.ch/jira/browse/ATLASPANDA-322?focusedCommentId=1413036&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1413036)

### CODE REVIEW

**Comment by PalNilsson** [comment]
Hi,
Why are you writing job parameters to the queue data file? Better to write them to a new file no?
Cheers, Paul

**Comment by complynx** [comment]
This file will be definitely there whatever is done and it will be parsed as necessary when I need my vars.

**Comment by PalNilsson** [comment]
Yes but it has nothing to do with jobs so it's the wrong place and you also had to write a new function to write to it. It's better if you create a new file. Use the writeJSON() function in FileHandling.py (and readJSON()).

**Comment by PalNilsson** [comment]
Please implement as suggested. Thanks, Paul

**Pull request closed without merging**
